// Code generated by protoc-gen-mcp-gateway. DO NOT EDIT.
// source: echo.proto

package main

import (
	"context"
	"fmt"

	"grpc-mcp-gateway/runtime"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"google.golang.org/protobuf/types/known/structpb"
)

// RegisterEchoServiceMCPGateway registers MCP tools for EchoService.
func RegisterEchoServiceMCPGateway(server *mcp.Server, client EchoServiceClient) {
	if server == nil {
		panic("mcp server is nil")
	}
	if client == nil {
		panic("grpc client is nil")
	}

	{
		tool := &mcp.Tool{
			Name:        "echo",
			Title:       "Echo",
			Description: "Echoes structured input back to the caller.",
			Annotations: &mcp.ToolAnnotations{ReadOnlyHint: true},
		}
		mcp.AddTool(server, tool, func(ctx context.Context, _ *mcp.CallToolRequest, args map[string]any) (*mcp.CallToolResult, any, error) {
			req := &structpb.Struct{}
			if err := runtime.DecodeArgs(args, req); err != nil {
				return runtime.ToolError(fmt.Sprintf("invalid arguments: %v", err)), nil, nil
			}
			resp, err := client.Echo(ctx, req)
			if err != nil {
				return runtime.ToolError(err.Error()), nil, nil
			}
			output, err := runtime.EncodeProto(resp)
			if err != nil {
				return runtime.ToolError(fmt.Sprintf("failed to encode response: %v", err)), nil, nil
			}
			return nil, output, nil
		})
	}
}
