// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: echo.proto

package main

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/structpb"
)

// EchoServiceClient is a minimal client interface used by the example.
type EchoServiceClient interface {
	Echo(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error)
}
